### ISSUE TITLE
How to uninstall PhpStrom in ubuntu 16.04

### ISSUE THREAD

**Issue by vishub** [JetBrains/phpstorm-workshop#40]

**Comment by MaXal** [comment]
Please remove the main folder and ~/.PhpStorm* folders. That should be enough. In future, please contact our support team (Help|New Support Request).

**Comment by behradkhodayar** [comment]
Just as a note here to stay:
There is one other option. Maybe you've installed PHPStorm as a **snap package**. Then as snap packages, _get mounted rather being unpacked_, there is no folder you can remove. So you have to use snap command to uninstall it. First check to see if its installed as a snap package: 
`sudo snap list`
If you see PHPStorm in list, then you've to uninstall it using:
`sudo snap remove PHPStorm`
make sure to type PHPStorm's name exactly as is, regarding character case.
---
Say, one side effect that you may notice is that number of loop devices in your directory view is decreased, because now you have one snap app less than before. :-)

**Comment by behradkhodayar** [comment]
Just as a note here to stay:
There is one other option. Maybe you've installed PHPStorm as a snap package. Then as snap packages, get mounted rather being unpacked, there is no folder you can remove. So you have to use snap command to uninstall it. First check to see if its installed as a snap package:

    sudo snap list

If you see PHPStorm in list, then you've to uninstall it using:

    sudo snap remove PHPStorm

make sure to type PHPStorm's name exactly as is, regarding character case.

**Comment by pierrealexaline** [comment]
Nice !

**Comment by NaeemSohrabi** [comment]
> Just as a note here to stay:
> There is one other option. Maybe you've installed PHPStorm as a snap package. Then as snap packages, get mounted rather being unpacked, there is no folder you can remove. So you have to use snap command to uninstall it. First check to see if its installed as a snap package:
> 
> ```
> sudo snap list
> ```
> 
> If you see PHPStorm in list, then you've to uninstall it using:
> 
> ```
> sudo snap remove PHPStorm
> ```
> 
> make sure to type PHPStorm's name exactly as is, regarding character case.

Thans it work's

**Comment by NaeemSohrabi** [comment]
Thanks, it work's
