### ISSUE TITLE
03 Inspections 01 Highlights: 5. Dead Code

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#74]
Nothing is highlighted or underlined, or what have you.

No other instruction than that it is dead code. Something should be visible, isn't it?

    // 5. Dead code (unused variable).
    public function deadCodeFunction1()
    {
        $variable = true;
    }

**Comment by zeitgen** [comment]
Yep, the variable should be highlighted as _unused_. 
Please make sure that you have the _Unused local variable_ enabled, it's in _Preferences | Editor | Inspections |PHP | Unused symbols | Unused local variable_.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/5338707/133580217-0e6ebefd-0bf7-4772-82df-752a465cbf3d.png">

**Comment by ASauer** [comment]
'Unused local variable' was already checked, but no highlight.
If I hover my mouse over the variable, I see it is an unused variable.
Should there be a scribbly line underneath or should the whole variable be highlight (while my cursor is somewhere else)?

**Comment by zeitgen** [comment]
Turns out, this set of _Unused_ inspections (Unused variable, unused parameter, etc.) uses a bit different coloring regulated by the color scheme; and the highlighting level set for the inspection only affects the markers in the scrollbar area on the right and the batch inspection results.

Sorry for confusion, here's another hint for you instead :D
 - Position the caret at some symbol in the editor (such as this unused `$variable`), press `CMD+Shift+A` to search for an action called "Jump to Colors and Fonts". This way, you can always figure out why some code element is styled in a certain way and tweak it all from there, too.

    <img width="420" alt="image" src="https://user-images.githubusercontent.com/5338707/133751325-0b2ac3d5-7693-4efb-baad-36da097a343e.png">
